### ISSUE TITLE
Feature: Proper Documentation

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [SylviBlossom/kristal#4]
Currently the current way of documentation that exist are 4 set images that document how to export the map (although it lacks the minimum object layers to make map playable at bare minimum) and some basic documentation of the Kristal's APis

**Comment by NyakoFox** [comment]
are you referring to the wiki? the documentation there is really good, i'm unsure what you'd want changed

**Comment by FriskTheFallenHuman** [comment]
oops, i'm sorry i didn't noticed that there's a wiki! my bad :sweat_smile:
